sonar.projectKey=goal-manager
sonar.projectName=Goal Manager
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000
sonar.login=sqp_3bb6ea33b3a978b2151ccf6513862394921313a3
sonar.passworcd = attri